version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: |
      sh -c "python /app/manage.py wait_for_db &&
             python /app/manage.py migrate &&
             python /app/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=localPasswordImadeNowNotForPrdoduction
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localPasswordImadeNowNotForPrdoduction
    ports:
      - "5432:5432"