version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - python/install-packages
      - setup_remote_docker:
        docker_layer_caching: true
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose up -d
      - run:
          name: Run django tests
          command: |
            pipenv run ./manage.py test